name: stewart_platform_control
description: "An app to control Stewart platform fluctuations."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hmi_core:
    git:
      url: https://github.com/a-givertzman/hmi_core.git
      ref: 2.0.0
  hmi_widgets:
    git:
      url: https://github.com/a-givertzman/hmi_widgets.git
      ref: 1.0.1
  hmi_networking:
    git:
      url: https://github.com/a-givertzman/hmi_networking.git
      ref: 1.1.0
  cma_registrator:
    git:
      url: https://github.com/a-givertzman/cma_registrator.git
      ref: 0.0.2
  fl_chart:
    git:
      url: https://github.com/a-givertzman/fl_chart.git
      ref: 0.63.0+2
  shared_preferences: ^2.2.3
  window_manager: ^0.4.3
  excel: ^4.0.6
  file_picker: ^8.1.4
  ditredi: ^2.0.2
  vector_math: ^2.1.4
  flutter_math_fork: ^0.7.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/settings/
    - assets/configs/
    - assets/visuals/

flutter_launcher_icons:
  image_path:  "assets/visuals/sine_rounded.png"
  windows:
    generate: true
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    icon_size: 256 # min:48, max:256, default: 48
