name: stewart_platform_control
description: "An app to control Stewart platform fluctuations."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hmi_core:
    git:
      url: https://github.com/a-givertzman/hmi_core.git
      ref: 2.0.0
  fl_chart:
    git:
      url: https://github.com/a-givertzman/fl_chart.git
      ref: 0.63.0+2
  shared_preferences: ^2.2.3
  toastification: ^1.2.1
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/visuals/sine.svg
    - assets/visuals/sine_rounded.png

flutter_launcher_icons:
  image_path:  "assets/visuals/sine_rounded.png"
  windows:
    generate: true
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    icon_size: 256 # min:48, max:256, default: 48
